apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kotoba-lab

build:
  artifacts:
    - image: kotoba-client
      docker:
        dockerfile: docker/Dockerfile.client
    - image: kotoba-server
      docker:
        dockerfile: docker/Dockerfile.server
  local:
    push: false

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: kotoba-client
    namespace: kotoba
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: kotoba-server
    namespace: kotoba
    port: 3001
    localPort: 3001
