apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotoba-client
  namespace: kotoba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kotoba-client
  template:
    metadata:
      labels:
        app: kotoba-client
    spec:
      containers:
        - name: client
          image: kotoba-client:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
