apiVersion: v1
kind: ConfigMap
metadata:
  name: kana-config
  namespace: kana
data:
  PORT: "3001"
  CORS_ORIGIN: "http://kana.local"
  OLLAMA_URL: "http://ollama.kana.svc.cluster.local:11434"
  OLLAMA_MODEL: "qwen2.5:3b"
